name: Build and Run C Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Install GTK development libraries
      run: sudo apt-get install -y libgtk-3-dev

    - name: Build and Run C Code
      run: gcc calculator.c -o calculator `pkg-config --cflags --libs gtk+-3.0` -lm && ./calculator
